[package]
name = "ipc-if"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.214", features = ["derive"] }
ts-rs = { version = "10.0.0", features = ["chrono-impl", "url", "uuid"] }
