// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GreetArgs = { name: string };

export type GreetLabel = 'greet';

export type GreetResponse = { message: string; timestamp: string };

export type GreetType = {
  args: GreetArgs;
  response: GreetResponse;
  label: GreetLabel;
};
